name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: xiaocuilin/xiaocuilin.github.io
        publish_dir: ./public
        publish_branch: master
        commitMessage: ${{ github.event.head_commit.message }}